# Ex110.2
"""Add to the currency.py module created in the precious challenges, a function called summary(), which shows on the screen some information generated by the functions we already have in the module created so far."""

import currency

print("\033[34m==\033[m" * 21)
price = float(input('Enter a price: '))
currency.summary(price, 80, 35)
print("\033[34m==\033[m" * 21)
print('xD')
