#Exercício009
x = int(input('Tabuada\nDigite um número: '))
t1 = str('{} x 1  = {:>2}'.format(x, x*1))
t2 = str('{} x 2  = {:>2}'.format(x, x*2))
t3 = str('{} x 3  = {:>2}'.format(x, x*3))
t4 = str('{} x 4  = {:>2}'.format(x, x*4))
t5 = str('{} x 5  = {:>2}'.format(x, x*5))
t6 = str('{} x 6  = {:>2}'.format(x, x*6))
t7 = str('{} x 7  = {:>2}'.format(x, x*7))
t8 = str('{} x 8  = {:>2}'.format(x, x*8))
t9 = str('{} x 9  = {:>2}'.format(x, x*9))
t0 = str('{} x 10 = {:>2}'.format(x, x*10))
print('-'*11)
print('{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}'.format(t1, t2, t3, t4, t5, t6, t7, t8, t9, t0))
print('-'*11)
print('xD')
