x = input('Digite algo:')
print('O tipo primitivo disso que você digito é:', type(x))
print('Está em maiúsculo:', x.isupper())
print('Está em minúsculo:', x.islower())
print('É um Alfanumérico:', x.isalnum())
print('É um número:', x.isnumeric())
print('É alfabético:', x.isalpha())
print('Está capitalizada:', x.istitle())
print('Só tem espaço?', x.isspace())
